body_link0:
  origin:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  geometry:
    mesh: "package://openarm_description/assets/robot/openarm_v2.0/meshes/body/visual/body_link0.dae"
    scale:
      x: 0.001
      y: 0.001
      z: 0.001
