base_link:
  origin:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: -0
    yaw: 0
  geometry:
    mesh: "package://openarm_description/assets/end_effector/pinch_gripper/meshes/visual/ee_base_link.dae"
    scale:
      x: 1
      y: 1
      z: 1
link1:
  origin:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: -0
    yaw: 0
  geometry:
    mesh: "package://openarm_description/assets/end_effector/pinch_gripper/meshes/visual/finger_inner.dae"
    scale:
      x: 1
      y: 1
      z: 1
link2:
  origin:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: -0
    yaw: 0
  geometry:
    mesh: "package://openarm_description/assets/end_effector/pinch_gripper/meshes/visual/finger_outter.dae"
    scale:
      x: 1
      y: 1
      z: 1
