grasp_frame:
  parent: base_link
  origin:
    x: -0.0219300000000009
    y: 0
    z: -0.138000000000019
    roll: 3.141592653589793
    pitch: 1.570796326794893
    yaw: 3.141592653589793
  meta:
    comment: grasp_frame
    source_joint:
      original_name: grasp_point
      canonical_name: null
      type: fixed
    parent_link:
      original_name: ee_base_link
      canonical_name: base_link
    child_link:
      original_name: grasp_frame
      canonical_name: null
